status: exit status: 0
child output:
	   0: backtrace_apple_no_dsymutil::main
	   1: core::ops::function::FnOnce::call_once
	   2: std::sys_common::backtrace::__rust_begin_short_backtrace
	   3: std::rt::lang_start::{{closure}}
	   4: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
	             at /rustc/46514218f6f31ad3a1510ecc32af47e9e486c27d/library/core/src/ops/function.rs:284:13
	   5: std::panicking::try::do_call
	             at /rustc/46514218f6f31ad3a1510ecc32af47e9e486c27d/library/std/src/panicking.rs:500:40
	   6: std::panicking::try
	             at /rustc/46514218f6f31ad3a1510ecc32af47e9e486c27d/library/std/src/panicking.rs:464:19
	   7: std::panic::catch_unwind
	             at /rustc/46514218f6f31ad3a1510ecc32af47e9e486c27d/library/std/src/panic.rs:142:14
	   8: std::rt::lang_start_internal::{{closure}}
	             at /rustc/46514218f6f31ad3a1510ecc32af47e9e486c27d/library/std/src/rt.rs:148:48
	   9: std::panicking::try::do_call
	             at /rustc/46514218f6f31ad3a1510ecc32af47e9e486c27d/library/std/src/panicking.rs:500:40
	  10: std::panicking::try
	             at /rustc/46514218f6f31ad3a1510ecc32af47e9e486c27d/library/std/src/panicking.rs:464:19
	  11: std::panic::catch_unwind
	             at /rustc/46514218f6f31ad3a1510ecc32af47e9e486c27d/library/std/src/panic.rs:142:14
	  12: std::rt::lang_start_internal
	             at /rustc/46514218f6f31ad3a1510ecc32af47e9e486c27d/library/std/src/rt.rs:148:20
	  13: std::rt::lang_start
	  14: main
	  15: __libc_start_call_main
	             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
	  16: __libc_start_main_impl
	             at ./csu/../csu/libc-start.c:392:3
	  17: _start
	
	
	
